### ISSUE TITLE
Last version breaks Markdown Jetpack module’s functionality

### ISSUE THREAD

**Issue by Li-An** [thanks-to-it/remove-special-characters-from-permalinks#1]
Hello, last version of the plugin breaks Markdown **Jetpack module** in **Classic Editor**. This module saves Markdown version of the content in `post_content_filtered field`. When **Remove Special Characters From Permalinks** is activated, it’s the HTML version that is saved in the field. So **Markdown** is lost. The problem did not occurred in previous version to my opinion.

**Comment by pablo-sg-pacheco** [comment]
Sorry for the delay again @Li-An ,
Thanks for letting me know that it's fixed now ;)

I'll just let it registered here that it's fixed on version 1.0.5
https://github.com/thanks-to-it/remove-special-characters-from-permalinks/releases/tag/1.0.5
